version: "3.8"

services:
  kata_sandbox_typescript:
    build: .
    container_name: "kata_sandbox_typescript"
    working_dir: "/usr/src/app"
    volumes:
      - ./:/usr/src/app:rw,Z
      - node_modules:/usr/src/app/node_modules:rw,Z
    tty: true

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
